/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/kunal15595/ros/ros_ws/src/server_tutorial/srv/Set_position.srv
 *
 */


#ifndef SERVER_TUTORIAL_MESSAGE_SET_POSITIONREQUEST_H
#define SERVER_TUTORIAL_MESSAGE_SET_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_tutorial
{
template <class ContainerAllocator>
struct Set_positionRequest_
{
  typedef Set_positionRequest_<ContainerAllocator> Type;

  Set_positionRequest_()
    : x(0)
    , y(0)  
    , z(0)
    , roll(0)
    , pitch(0)
    , yaw(0){
    }
  Set_positionRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  
    , z(0)
    , roll(0)
    , pitch(0)
    , yaw(0){
    }


   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

     typedef int64_t _z_type;
  _z_type z;

     typedef int64_t _roll_type;
  _roll_type roll;

     typedef int64_t _pitch_type;
  _pitch_type pitch;

     typedef int64_t _yaw_type;
  _yaw_type yaw;


  typedef boost::shared_ptr< ::server_tutorial::Set_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_tutorial::Set_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Set_positionRequest_

typedef ::server_tutorial::Set_positionRequest_<std::allocator<void> > Set_positionRequest;

typedef boost::shared_ptr< ::server_tutorial::Set_positionRequest > Set_positionRequestPtr;
typedef boost::shared_ptr< ::server_tutorial::Set_positionRequest const> Set_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_tutorial::Set_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace server_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'server_tutorial': ['/home/kunal15595/ros/ros_ws/src/server_tutorial/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_tutorial::Set_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_tutorial::Set_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_tutorial::Set_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::server_tutorial::Set_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_tutorial/Set_positionRequest";
  }

  static const char* value(const ::server_tutorial::Set_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
int64 z\n\
int64 roll\n\
int64 pitch\n\
int64 yaw\n\
";
  }

  static const char* value(const ::server_tutorial::Set_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);

    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Set_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_tutorial::Set_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_tutorial::Set_positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<int64_t>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<int64_t>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_TUTORIAL_MESSAGE_SET_POSITIONREQUEST_H
