/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/kunal15595/ros/ros_ws/src/gazebo_ros_plugin/srv/Set_activation.srv
 *
 */


#ifndef GAZEBO_ROS_PLUGIN_MESSAGE_SET_ACTIVATION_H
#define GAZEBO_ROS_PLUGIN_MESSAGE_SET_ACTIVATION_H

#include <ros/service_traits.h>


#include "/home/luis/catkin_ws/src/gazebo_ros_plugin/include/gazebo_ros_plugin/Set_activationRequest.h"
#include "/home/luis/catkin_ws/src/gazebo_ros_plugin/include/gazebo_ros_plugin/Set_activationResponse.h"


namespace gazebo_ros_plugin
{

struct Set_activation
{

typedef Set_activationRequest Request;
typedef Set_activationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Set_activation
} // namespace gazebo_ros_plugin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_plugin::Set_activation > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::gazebo_ros_plugin::Set_activation&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_plugin::Set_activation > {
  static const char* value()
  {
    return "gazebo_ros_plugin/Set_activation";
  }

  static const char* value(const ::gazebo_ros_plugin::Set_activation&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_plugin::Set_activationRequest> should match 
// service_traits::MD5Sum< ::gazebo_ros_plugin::Set_activation > 
template<>
struct MD5Sum< ::gazebo_ros_plugin::Set_activationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_plugin::Set_activation >::value();
  }
  static const char* value(const ::gazebo_ros_plugin::Set_activationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_plugin::Set_activationRequest> should match 
// service_traits::DataType< ::gazebo_ros_plugin::Set_activation > 
template<>
struct DataType< ::gazebo_ros_plugin::Set_activationRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_plugin::Set_activation >::value();
  }
  static const char* value(const ::gazebo_ros_plugin::Set_activationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_plugin::Set_activationResponse> should match 
// service_traits::MD5Sum< ::gazebo_ros_plugin::Set_activation > 
template<>
struct MD5Sum< ::gazebo_ros_plugin::Set_activationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_plugin::Set_activation >::value();
  }
  static const char* value(const ::gazebo_ros_plugin::Set_activationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_plugin::Set_activationResponse> should match 
// service_traits::DataType< ::gazebo_ros_plugin::Set_activation > 
template<>
struct DataType< ::gazebo_ros_plugin::Set_activationResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_plugin::Set_activation >::value();
  }
  static const char* value(const ::gazebo_ros_plugin::Set_activationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_PLUGIN_MESSAGE_SET_POSITION_H
