/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/kunal15595/ros/ros_ws/src/gazebo_ros_plugin/srv/Set_activation.srv
 *
 */


#ifndef GAZEBO_ROS_PLUGIN_MESSAGE_SET_ACTIVATIONRESPONSE_H
#define GAZEBO_ROS_PLUGIN_MESSAGE_SET_ACTIVATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_ros_plugin
{
template <class ContainerAllocator>
struct Set_activationResponse_
{
  typedef Set_activationResponse_<ContainerAllocator> Type;

  Set_activationResponse_()
    : resu(0)  {
    }
  Set_activationResponse_(const ContainerAllocator& _alloc)
    : resu(0)  {
    }



   typedef int64_t _resu_type;
  _resu_type resu;




  typedef boost::shared_ptr< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Set_activationResponse_

typedef ::gazebo_ros_plugin::Set_activationResponse_<std::allocator<void> > Set_activationResponse;

typedef boost::shared_ptr< ::gazebo_ros_plugin::Set_activationResponse > Set_activationResponsePtr;
typedef boost::shared_ptr< ::gazebo_ros_plugin::Set_activationResponse const> Set_activationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gazebo_ros_plugin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gazebo_ros_plugin': ['/home/kunal15595/ros/ros_ws/src/gazebo_ros_plugin/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_ros_plugin/Set_activationResponse";
  }

  static const char* value(const ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 resu\n\
\n\
";
  }

  static const char* value(const ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Set_activationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_ros_plugin::Set_activationResponse_<ContainerAllocator>& v)
  {
    s << indent << "resu: ";
    Printer<int64_t>::stream(s, indent + "  ", v.resu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_ROS_PLUGIN_MESSAGE_SET_ACTIVATIONRESPONSE_H
